### ISSUE TITLE
hadoop depency for druid should be renamed

### ISSUE THREAD

**Issue by starblood** [druid-io/docker-druid#18]
I encountered error there is no such file or directory for hadoop_dependencies while build image.

in Dockerfile

below line should be
```bash
RUN cp -r distribution/target/hadoop_dependencies /usr/local/druid/
```
like this.
```bash
RUN cp -r distribution/target/hadoop-dependencies /usr/local/druid/
```

**Comment by fjy** [comment]
@starblood do you mind contributing the fix here? https://github.com/druid-io/docker-druid/blob/master/Dockerfile

**Comment by guobingkun** [comment]
Hi @starblood , thanks for reporting the issue! I've sent #19 to address it. Please let me know if there is any other issue.

**Comment by starblood** [comment]
:+1:
