### ISSUE TITLE
Can't build docker image

### ISSUE THREAD

**Issue by luluprat** [druid-io/docker-druid#3]
I try to build the docker image and it fail evry time with this error :

---> cbf04910b89a
Removing intermediate container 67eb999231f6
Step 20 : RUN /etc/init.d/mysql start && echo "GRANT ALL ON druid.* TO 'druid'@'localhost' IDENTIFIED BY 'diurd'; CREATE database druid CHARACTER SET utf8;" | mysql -u root && /etc/init.d/mysql stop
 ---> Running in bfabd965d3f9
2015/04/17 09:19:18 /var/lib/docker/aufs/mnt/bfabd965d3f93f4aaaf7b93160a9dfd07c04a875b03e7607da0f6ec03b820080 is not within /var/lib/docker/aufs/mnt/bfabd965d3f93f4aaaf7b93160a9dfd07c04a875b03e7607da0f6ec03b820080

**Comment by xvrl** [comment]
what version of Docker are you using?

**Comment by luluprat** [comment]
docker -v
Docker version 1.0.1, build 990021a

**Comment by xvrl** [comment]
@luluprat sorry for the late response, I think you might want to try a more recent version of Docker such as 1.5 or 1.6.
